### ISSUE TITLE
AMS Slots are unknown in LAN mode for custom filaments

### ISSUE THREAD

**Issue by Timsche2210** [greghesp/ha-bambulab#1116]
Hi,

I have the issue that the AMS slots are unknown:

![Image](https://github.com/user-attachments/assets/5a4efe69-4a05-4718-b0e2-c341be6bcd8f)
![Image](https://github.com/user-attachments/assets/46d23c94-b55f-4084-a05b-c6806e19c32e)

I use the latest version of HA; Bambu Lab etc

After deleting and reconfiguration the same issue exists.

At new config I can only use LAN Mode or Cloud. (I use LAN mode w/o any other issues)

Any ideas?

**Comment by AdrianGarside** [comment]
Are those all custom filaments?

**Comment by Timsche2210** [comment]
Yes.
By a friend of mine it looks like this:
![image](https://github.com/user-attachments/assets/931f8afe-4a0e-476c-9c7a-0ba4e1d9af24)

**Comment by Timsche2210** [comment]
He has here a 3rd option with connection via mail, which I havent?

![Image](https://github.com/user-attachments/assets/1c141d16-c83c-46e9-9de8-da5a63309098)

**Comment by AdrianGarside** [comment]
There's a fix coming to show the type of the filament if the name isn't known. But we get the name for custom filaments from a Bambu Lab Cloud REST API so if you're in pure LAN mode that's not available. So no names for custom filaments.

**Comment by t3chguy** [comment]
@AdrianGarside if a printer is in LAN only mode so connecting `Bambu Lab-Cloud` mode finds no printers, how is a user meant to have support for custom filaments? I don't see a way to add an account unless the printer is attached to that account

**Comment by AdrianGarside** [comment]
> He has here a 3rd option with connection via mail, which I havent?
> 
> ![Image](https://github.com/user-attachments/assets/1c141d16-c83c-46e9-9de8-da5a63309098)

You get that if you have connected any of your printers to Bambu cloud. It then offers to reused the existing authentication.

**Comment by AdrianGarside** [comment]
The fix I mentioned is in 2.1.8-beta4

**Comment by AdrianGarside** [comment]
> [@AdrianGarside](https://github.com/AdrianGarside) if a printer is in LAN only mode so connecting `Bambu Lab-Cloud` mode finds no printers, how is a user meant to have support for custom filaments? I don't see a way to add an account unless the printer is attached to that account
> 
> This is going to be more important with the new firmware updates where the only way to use tools like Orcaslicer will be Developer LAN only mode.

Yes that is one of the ways Bambu is screwing customers by requiring them to use lan mode to opt out of their anti-consumer blocks. I’ll be looking into whether I can record custom filament information out of the 3mf as I observe it in prints in order to back fill but I don’t know yet if there’s enough information in there as I’ve been busy with other higher priority feature additions to close other lan mode gaps.

**Comment by t3chguy** [comment]
X1, printer knows the brand etc of my custom filaments

**Comment by AdrianGarside** [comment]
Does it know the brand of a custom filament you've never printed with yet?

Looking at the project_settings.confing in the 3mf file sent to the printer it looks like it does have enough information for me to find, collate and record custom filaments for later re-use.

**Comment by t3chguy** [comment]
Yes but that may be from prior to me LAN-mode-ing it, as that only happened when BL shipped that Beta firmware that angered everyone, and all of my custom filaments predate that.

![Image](https://github.com/user-attachments/assets/5fc967fe-a4eb-4610-a378-9e01ecdbed88)

I will try create a new custom filament after this print is over to test further.

**Comment by AdrianGarside** [comment]
The test I'm interested in is whether simply creating the custom filament and setting it into one of the AMS slots is enough for the printer to know the name. If that doesn't work, does the name appear when you print. And if that doesn't work it sounds likely that it's knowledge of custom filaments came from a cache from the before times.

**Comment by t3chguy** [comment]
Even if the printer doesn't know the name, given it gives us the ID and we can match the ID against the cloud, I don't mind ha-bambulab being BL-cloud connected, as long as they don't control my printer, assuming BL will still let us query my slicer settings.

**Comment by AdrianGarside** [comment]
I'll give that some thought. The way it's setup currently if you give cloud credentials the printer is expected be cloud connected. You can set local mqtt connection but the printer itself is still cloud connected and so Bambu's block of 3rd party integrations under a laughable security argument is still in play.

What I'm seeing in practice is that the custom filament lookup is more fragile than the cloud mqtt connection - the provided credentials are stopping working for the former way earlier than they should while still continuing to work for the latter. That led to people seeing custom filaments silently stopping working while there were no other problems as I wasn't surfacing connection failure for the custom filaments separately.

**Comment by AdrianGarside** [comment]
Looks like I can get everything I need from the project_settings.config file:
```
{
    "filament_colour": [
        "#161616"
    ],
    "filament_cost": [
        "20"
    ],
    "filament_density": [
        "1.24"
    ],
    "filament_ids": [
        "P9816594"
    ],
    "filament_settings_id": [
        "ELEGOO PLA Black @Bambu Lab P1S 0.6 nozzle"
    ],
    "filament_type": [
        "PLA"
    ],
    "filament_vendor": [
        "ELEGOO"
    ],
    "nozzle_temperature_range_high": [
        "240"
    ],
    "nozzle_temperature_range_low": [
        "190"
    ]
}
```

**Comment by AdrianGarside** [comment]
I'm opening a separate issue to cover that feature addition. The specific issue logged originally here is addressed in 2.1.8.

**Comment by AdrianGarside** [comment]
Actually this is more the lan mode custom filament issue. I only fixed it to show filament type instead of unknown which is an improvement but not the full deal. I'll keep using this one.

**Comment by t3chguy** [comment]
![Image](https://github.com/user-attachments/assets/f743810c-3c7b-4ff7-82a8-563f0c5d7169)

Adding a new custom filament, the filament colour & type are shown in the printer but manufacturer and model are blank.

After sending a print to the machine using the newly added (and synced) filament the printer is still unable to identify it. So if you can pull this data out of the gcode then that's going to beat the functionality of the printer itself 👏 

![Image](https://github.com/user-attachments/assets/4cc5dd2c-c383-44eb-9288-ad728580c230)

does look like the exported 3mf has the filament profiles included given I get this warning trying to view it.

**Comment by AdrianGarside** [comment]
Great! Just need to find some time to write the code to store the custom filaments into home assistant storage ideally in a shared location and in a way that multiple instances can safely read/write to it without corrupting it.

**Comment by miguelangellv** [comment]
Maybe we need the hybrid option: Bambulab Account for filaments and local for printers.

**Comment by Jokemachine** [comment]
how to get a custom filament name in my ams tray? it used to work fine. then p1s disappeared, and I was connected via LAN and cloud at the same time. without the cloud, there is no name for the custom coils in the card. and it doesn't work at all without LAN.

<img width="484" height="214" alt="Image" src="https://github.com/user-attachments/assets/9b379df4-5969-4148-9d08-c89466646afc" /> 

<img width="970" height="965" alt="Image" src="https://github.com/user-attachments/assets/b2dbe1e0-484a-49d6-ba12-46da96755d8b" />
custom filament, he just signs it -TYPE.
and the one who knows writes the name

**Comment by AdrianGarside** [comment]
I’m not psychic. Add a diagnostics log.

**Comment by Jokemachine** [comment]
[home-assistant_bambu_lab_2026-04-14T09-04-04.748Z.log](https://github.com/user-attachments/files/26704034/home-assistant_bambu_lab_2026-04-14T09-04-04.748Z.log)

2026-04-14 01:25:10.428 ERROR (Recorder) [homeassistant] Error doing job: Task exception was never retrieved (task: None)
Traceback (most recent call last):
  File "/config/custom_components/bambu_lab/coordinator.py", line 303, in _handle_service_call_event
    future.set_result(result)
    ~~~~~~~~~~~~~~~~~^^^^^^^^
asyncio.exceptions.InvalidStateError: invalid state

2026-04-13 23:50:49.216 ERROR (MainThread) [custom_components.bambu_lab] Service call timed out
2026-04-13 23:50:49.216 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547621161856] Error during service call to bambu_lab.get_filament_data: Failed to process the returned action response data, expected a dictionary, but got <class 'NoneType'>

2026-04-13 23:49:38.173 ERROR (MainThread) [frontend.js.modern.202603257] Uncaught error from Chrome 147.0.0.0 on Windows 10.0
TypeError: Cannot read properties of undefined (reading 'model')
f.set (/bambu_lab/ha-bambulab-cards.js:76:441540)
