### ISSUE TITLE
Reprint from cache failing (H2S? USB cache related?)

### ISSUE THREAD

**Issue by AdrianGarside** [greghesp/ha-bambulab#1512]
> @AdrianGarside 
> Works fine for me except printing from cache and the custom Filament names doesnt show up, just a generic name:
> 
> <img width="481" height="475" alt="Image" src="https://github.com/user-attachments/assets/9563068a-bbe3-470d-9db8-078f4c47d11e" />
> 
> I'm quite sure the Names were right, as long as i use the Cloud mode.
> 
> 
> I use LAN only mode
> Files are in cache folder and showing up, but when I try to print a file i got the following error message:
> FYI: I use the feature to store the files on USB-Stick after upload if thats the problem.
> 
> <img width="799" height="487" alt="Image" src="https://github.com/user-attachments/assets/c1340de8-866f-4026-9cd6-c2b044e8e2fa" />
> 
> and log says:
> ```
> 2025-09-08 12:28:16.434 DEBUG (MainThread) [custom_components.bambu_lab] Print history response: 3 files from 1 printers
> 2025-09-08 12:28:16.434 DEBUG (MainThread) [custom_components.bambu_lab] {'files': [{'filename': 'OrcaCube_v3.gcode.3mf', 'path': '0938BC562600476/prints/OrcaCube_v3.gcode.3mf', 'type': 'prints', 'size': 574059, 'size_human': '560.6 KB', 'modified': '2025-09-08T11:33:01.686296', 'thumbnail_path': '0938BC562600476/prints/OrcaCube_v3.gcode.png', 'printer_serial': '0938BC562600476', 'printer_device_id': '8ef15e300d2d346ed51bde9c4b67998f', 'printer_name': 'H2S_0938BC562600476', 'printer_model': 'H2S'}, {'filename': 'Bambu_Scraper_Grip.gcode.3mf', 'path': '0938BC562600476/prints/Bambu_Scraper_Grip.gcode.3mf', 'type': 'prints', 'size': 631234, 'size_human': '616.4 KB', 'modified': '2025-09-08T11:05:16.250172', 'thumbnail_path': '0938BC562600476/prints/Bambu_Scraper_Grip.gcode.png', 'printer_serial': '0938BC562600476', 'printer_device_id': '8ef15e300d2d346ed51bde9c4b67998f', 'printer_name': 'H2S_0938BC562600476', 'printer_model': 'H2S'}, {'filename': 'black&white.gcode.3mf', 'path': '0938BC562600476/prints/cache/black&white.gcode.3mf', 'type': 'prints', 'size': 631396, 'size_human': '616.6 KB', 'modified': '2025-09-08T10:47:59.951585', 'thumbnail_path': '0938BC562600476/prints/cache/black&white.gcode.png', 'printer_serial': '0938BC562600476', 'printer_device_id': '8ef15e300d2d346ed51bde9c4b67998f', 'printer_name': 'H2S_0938BC562600476', 'printer_model': 'H2S'}], 'total_files': 3, 'total_size_bytes': 1836689, 'total_printers': 1, 'timestamp': '2025-09-08T12:28:16.434269'}
> 2025-09-08 12:28:16.437 DEBUG (MainThread) [custom_components.bambu_lab] Video response: 2 videos from 1 printers
> 2025-09-08 12:28:16.437 DEBUG (MainThread) [custom_components.bambu_lab] {'videos': [{'filename': 'video_2025-09-08_17-34-43.mp4', 'path': '0938BC562600476/timelapse/video_2025-09-08_17-34-43.mp4', 'type': 'timelapse', 'size': 4922128, 'size_human': '4.7 MB', 'modified': '2025-09-08T12:04:18.208924', 'thumbnail_path': '0938BC562600476/timelapse/video_2025-09-08_17-34-43.jpg', 'printer_serial': '0938BC562600476', 'printer_device_id': '8ef15e300d2d346ed51bde9c4b67998f', 'printer_name': 'H2S_0938BC562600476', 'printer_model': 'H2S'}, {'filename': 'video_2025-09-08_15-28-02.mp4', 'path': '0938BC562600476/timelapse/video_2025-09-08_15-28-02.mp4', 'type': 'timelapse', 'size': 2092025, 'size_human': '2.0 MB', 'modified': '2025-09-08T10:48:00.320585', 'thumbnail_path': '0938BC562600476/timelapse/video_2025-09-08_15-28-02.jpg', 'printer_serial': '0938BC562600476', 'printer_device_id': '8ef15e300d2d346ed51bde9c4b67998f', 'printer_name': 'H2S_0938BC562600476', 'printer_model': 'H2S'}], 'total_videos': 2, 'total_size_bytes': 7014153, 'total_printers': 1, 'timestamp': '2025-09-08T12:28:16.437104'}
> 2025-09-08 12:28:21.378 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 280, in _handle_refresh_interval
>     await self._async_refresh(log_failures=True, scheduled=True)
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 491, in _async_refresh
>     self.async_update_listeners()
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 190, in async_update_listeners
>     update_callback()
>     ~~~~~~~~~~~~~~~^^
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 571, in _handle_coordinator_update
>     self.async_write_ha_state()
>     ~~~~~~~~~~~~~~~~~~~~~~~~~^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1026, in async_write_ha_state
>     self._async_write_ha_state()
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1151, in _async_write_ha_state
>     self.__async_calculate_state()
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1088, in __async_calculate_state
>     state = self._stringify_state(available)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1032, in _stringify_state
>     if (state := self.state) is None:
>                  ^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 560, in state
>     value = self.native_value
>             ^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/eero/sensor.py", line 396, in native_value
>     return self.entity_description.native_value(self.resource, self.entity_description.key)
>            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/eero/sensor.py", line 159, in <lambda>
>     native_value=lambda resource, key: (getattr(resource, key)[0] + getattr(resource, key)[1]),
>                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
> TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
> 2025-09-08 12:28:21.650 INFO (MainThread) [custom_components.bambu_lab] EnsureCacheFileAPIView called: serial=0938BC562600476, cache_path=0938BC562600476/prints/OrcaCube_v3.gcode.3mf, expected_size=574059
> ```
>  

 _Originally posted by @StefanX13 in [#1506](https://github.com/greghesp/ha-bambulab/issues/1506#issuecomment-3265675421)_

**Comment by StefanX13** [comment]
Sorry for the delay.
This ist the folder structure when connected with ftp:
<img width="472" height="664" alt="Image" src="https://github.com/user-attachments/assets/a61ce801-f315-4fab-af7b-0001ab2c7828" />
And this is inside the Cache folder:

<img width="583" height="730" alt="Image" src="https://github.com/user-attachments/assets/bd0f7f4a-dee7-4152-8eb1-93d9eb31890e" />

The last changed file in the cache folder is different from the last file in the root folder, which seems to be content of the USB Stick

PS: I tried to disable the USB-Upload feature started a Print from Bambu studio and then tried to reprint the file from HA. The result and error message is the same.

**Comment by StefanX13** [comment]
Corrected the 2nd screenshot.
@AdrianGarside Do you need anything else?

**Comment by bandesz** [comment]
I have the same error on a P1S when I try to reprint something, that the printer already printed. LAN mode only.

**Comment by SeventhUnderhand** [comment]
> I have the same error on a P1S when I try to reprint something, that the printer already printed. LAN mode only.

I am also getting the same thing when printing from a P1S. I also can't seem to locate the option to adjust model cache count on home assistant. Printer is in LAN Developer mode

Edit: found the option to change the cache. Set it to -1 and still have the same error

**Comment by AdrianGarside** [comment]
This should be specific to prints coming from Orca and fixed in 2.2.1.

**Comment by StefanX13** [comment]
> This should be specific to prints coming from Orca and fixed in 2.2.1.

@AdrianGarside 
I Print from bambu studio and reported the error in My h2s feature request. Are you sure that 2.2.1 fixes the error for h2s with bambu studio as well? 

Ps I'm on 2.2.1 beta2 and the error persists

**Comment by AdrianGarside** [comment]
No. The issue I’ve fixed is that files that were on the root of the printer (not in the \cache folder weren’t printable. Orca puts them in the root and I have never seen Bambu Studio do that for a normal print, not sure about sending files though. Can you retest with that fix in place and grab diagnostic and debug logs if it’s still broken for you?

**Comment by bandesz** [comment]
I used Bambu Studio and sent the file to the printer. It is saved in the root folder. This behaviour is the same in Bambu Studio/Orca.

**Comment by StefanX13** [comment]
Made a quick test while i deleted all files in the cache folder before printing. Than started a Print from bambu studio, the file only appears in the root folder of the printer, cache still empty after printing.
Currently updating to 2.2.1 and will make a test with logs after restarting HA

**Comment by StefanX13** [comment]
@AdrianGarside 
Printing still not possible but the error from my screenshot related to the cache ("Failed to upload ... cache past...") is gone.
Error Log from Debugging while try to start the print: 
[home-assistant_bambu_lab_2025-09-12T04-39-54.269Z.log](https://github.com/user-attachments/files/22289694/home-assistant_bambu_lab_2025-09-12T04-39-54.269Z.log)

Diag:
[config_entry-bambu_lab-01K42V5SBXK7FE4355BE81RM8H (2).json](https://github.com/user-attachments/files/22291410/config_entry-bambu_lab-01K42V5SBXK7FE4355BE81RM8H.2.json)

This error message pops up in bambu studio when its opened while try to start the print from HA. Print also failes when Bambu studio is not open while try to start the print btw..
<img width="352" height="214" alt="Image" src="https://github.com/user-attachments/assets/7e5caae9-5331-4d8c-a05d-21bd005ea7e6" />

Edit: added Diag output

**Comment by AdrianGarside** [comment]
> I used Bambu Studio and sent the file to the printer. It is saved in the root folder. This behaviour is the same in Bambu Studio/Orca.

Weird. When I print from Bambu Studio it always ends up in the cache subfolder (P1/X1s).

**Comment by AdrianGarside** [comment]
> [@AdrianGarside](https://github.com/AdrianGarside) Printing still not possible but the error from my screenshot related to the cache ("Failed to upload ... cache past...") is gone. Error Log from Debugging while try to start the print: [home-assistant_bambu_lab_2025-09-12T04-39-54.269Z.log](https://github.com/user-attachments/files/22289694/home-assistant_bambu_lab_2025-09-12T04-39-54.269Z.log)
> 
> Diag: [config_entry-bambu_lab-01K42V5SBXK7FE4355BE81RM8H (2).json](https://github.com/user-attachments/files/22291410/config_entry-bambu_lab-01K42V5SBXK7FE4355BE81RM8H.2.json)
> 
> This error message pops up in bambu studio when its opened while try to start the print from HA. Print also failes when Bambu studio is not open while try to start the print btw.. <img alt="Image" width="352" height="214" src="https://private-user-images.githubusercontent.com/2234517/488653687-7e5caae9-5331-4d8c-a05d-21bd005ea7e6.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTc2OTQyODcsIm5iZiI6MTc1NzY5Mzk4NywicGF0aCI6Ii8yMjM0NTE3LzQ4ODY1MzY4Ny03ZTVjYWFlOS01MzMxLTRkOGMtYTA1ZC0yMWJkMDA1ZWE3ZTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDkxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA5MTJUMTYxOTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjAyYjEyNzc2ZmMwODkwYjFiZmQyYjU5NmZiY2Y4NzM5NTJkODZhYmQ3YzczOWU0ODk4MmQyN2NlNjE2ZDA0YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.u857l8mFs5rusbLd5na9Iyy4aH9A6842FbhnTubB-lg">
> 
> Edit: added Diag output

IIRC that's the failure symptom if the ams mapping isn't correct. Can you tell me more about the original model specifically how the filaments were setup during the print? And can you unzip it (rename 3mf extension to zip) and provide the contained slice_info.config file?

**Comment by bandesz** [comment]
@AdrianGarside I mean I didn’t print from Bambu Studio, but used the “send file” option instead

**Comment by StefanX13** [comment]
> > [@AdrianGarside](https://github.com/AdrianGarside) Printing still not possible but the error from my screenshot related to the cache ("Failed to upload ... cache past...") is gone. Error Log from Debugging while try to start the print: [home-assistant_bambu_lab_2025-09-12T04-39-54.269Z.log](https://github.com/user-attachments/files/22289694/home-assistant_bambu_lab_2025-09-12T04-39-54.269Z.log)
> > Diag: [config_entry-bambu_lab-01K42V5SBXK7FE4355BE81RM8H (2).json](https://github.com/user-attachments/files/22291410/config_entry-bambu_lab-01K42V5SBXK7FE4355BE81RM8H.2.json)
> > This error message pops up in bambu studio when its opened while try to start the print from HA. Print also failes when Bambu studio is not open while try to start the print btw.. <img alt="Image" width="352" height="214" src="https://private-user-images.githubusercontent.com/2234517/488653687-7e5caae9-5331-4d8c-a05d-21bd005ea7e6.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTc2OTQyODcsIm5iZiI6MTc1NzY5Mzk4NywicGF0aCI6Ii8yMjM0NTE3LzQ4ODY1MzY4Ny03ZTVjYWFlOS01MzMxLTRkOGMtYTA1ZC0yMWJkMDA1ZWE3ZTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDkxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA5MTJUMTYxOTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjAyYjEyNzc2ZmMwODkwYjFiZmQyYjU5NmZiY2Y4NzM5NTJkODZhYmQ3YzczOWU0ODk4MmQyN2NlNjE2ZDA0YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.u857l8mFs5rusbLd5na9Iyy4aH9A6842FbhnTubB-lg">
> > Edit: added Diag output
> 
> IIRC that's the failure symptom if the ams mapping isn't correct. Can you tell me more about the original model specifically how the filaments were setup during the print? And can you unzip it (rename 3mf extension to zip) and provide the contained slice_info.config file?

Tested it again to be sure that i doesnt select the wrong filament. Used another file this time. Chosen filamtn in HA is the same as in the file sliced and still in the same AMS SLot. Here are the log and diagnostic:

[home-assistant_bambu_lab_2025-09-12T19-33-47.583Z.log](https://github.com/user-attachments/files/22304629/home-assistant_bambu_lab_2025-09-12T19-33-47.583Z.log)

[config_entry-bambu_lab-01K42V5SBXK7FE4355BE81RM8H (3).json](https://github.com/user-attachments/files/22304564/config_entry-bambu_lab-01K42V5SBXK7FE4355BE81RM8H.3.json)

Slice Info Config file (.txt for upload):
[slice_info.config.txt](https://github.com/user-attachments/files/22304647/slice_info.config.txt)

The file was sliced in Bambu Studio. One filament chosen from AMS for slicing. Chose the same (also same Slot) while try to reprint it from HA.

<img width="301" height="166" alt="Image" src="https://github.com/user-attachments/assets/2dc9622e-a53c-42b3-899e-cde3acb18634" />

This message poped up in Bambu Studio during the test:
<img width="364" height="157" alt="Image" src="https://github.com/user-attachments/assets/99664676-7bd2-479c-8d9a-314561fcbcc1" />

<img width="472" height="40" alt="Image" src="https://github.com/user-attachments/assets/8101957e-7670-443a-869d-4fe9b5292d96" />

**Comment by StefanX13** [comment]
Since the last Test i posted i printed 3 more models. Cache folder still empty when looking it up with FTP. All new files are in the root folder which seems to be the USB-Drive. Can't check it since it wont open/recognized on MacOs.

Btw. In contrast to Bandesz I use the Print Option in Bambu Studio, NOT the send file option

**Comment by AdrianGarside** [comment]
"Unsupported print file path or name. Please resend the print job." 

Is/was the file present in the root of the ftp? It does appear to be from the logs. This was the model file in the logs your provided:
'Herbst_Blätter_und_Pilze_Tisch_Deko.gcode.3mf'

Nothing stands out as obviously wrong.
file:///sdcard/Herbst_Blätter_und_Pilze_Tisch_Deko.gcode.3mf
Should work.

You might need to experiment with manual reprinting attempts using the print_project_file automation. I had to change the URL I provided to:
file:///sdcard/Herbst_Blätter_und_Pilze_Tisch_Deko.gcode.3mf
To work for files in sub-directories. I wonder if that _doesn't_ work for files in the root. Or maybe doesn't work for H2 printers. Previously it was:
ftp://{file}
But that only worked if the file was in the root directory.

**Comment by StefanX13** [comment]
> "Unsupported print file path or name. Please resend the print job."
> 
> Is/was the file present in the root of the ftp? It does appear to be from the logs. This was the model file in the logs your provided: 'Herbst_Blätter_und_Pilze_Tisch_Deko.gcode.3mf'
> 
> Nothing stands out as obviously wrong. file:///sdcard/Herbst_Blätter_und_Pilze_Tisch_Deko.gcode.3mf Should work.
> 
> You might need to experiment with manual reprinting attempts using the print_project_file automation. I had to change the URL I provided to: file:///sdcard/Herbst_Blätter_und_Pilze_Tisch_Deko.gcode.3mf To work for files in sub-directories. I wonder if that _doesn't_ work for files in the root. Or maybe doesn't work for H2 printers. Previously it was: ftp://{file} But that only worked if the file was in the root directory.

The file was in the root directory. Or at least this is how it appears through ftp

Could you please guide me how i test this with the mentioned automation? When i try to alter the path, regardless of using yaml or UI, it always starts with "file:///sdcard" regardless which path i provide like in this example from the Debug:
```
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
2025-09-14 10:27:09.218 ERROR (MainThread) [custom_components.frigate.api] Error fetching information from http://192.168.178.97:5000/api/stats: Cannot connect to host 192.168.178.97:5000 ssl:False [Connect call failed ('192.168.178.97', 5000)]
2025-09-14 10:27:39.670 DEBUG (MainThread) [custom_components.bambu_lab] handle_service_call: print_project_file
2025-09-14 10:27:39.671 DEBUG (MainThread) [custom_components.bambu_lab.pybambu] Sent {'print': {'sequence_id': 0, 'command': 'project_file', 'param': 'Metadata/plate_1.gcode', 'url': '**file:///sdcard/ftp://sdcard/Drill_Dust_Collector_And_Guide.gcode.3mf',** 'bed_type': 'auto', 'timelapse': False, 'bed_leveling': True, 'flow_cali': False, 'vibration_cali': True, 'layer_inspect': False, 'use_ams': True, 'ams_mapping': [3], 'subtask_name': 'Drill_Dust_Collector_And_Guide.gcode.3mf', 'profile_id': '0', 'project_id': '0', 'subtask_id': '0', 'task_id': '0'}} to topic device/0938BC562600476/request
2025-09-14 10:27:39.672 DEBUG (MainThread) [custom_components.bambu_lab] Service call result: False
2025-09-14 10:27:39.797 DEBUG (H2S-Mqtt-364) [custom_components.bambu_lab.pybambu] SUBTASK_NAME: Drill_Dust_Collector_And_Guide.gcode.3mf
2025-09-14 10:27:40.933 DEBUG (H2S-Mqtt-364) [custom_components.bambu_lab.pybambu] SUBTASK_NAME: 
```
Here i tried to start the print with "ftp://sdcard/Drill_Dust_Collector_And_Guide.gcode.3mf" when I try to start the print with annother path, it alway provided the path with starting "file:///sdcard". Maybe i'm to stupid to understand the syntax, so please give me a hint. Thanks in advance!

Additional Info. Now I also tried how it behaves when no USB-Stick is attached. When connected by FTP it doesnt show anything and copying isn't possible. When i try to print something from Bambu Studio i got the following error message:

<img width="694" height="301" alt="Image" src="https://github.com/user-attachments/assets/9841e84a-67d8-40ec-bef7-b5ba797e2a7c" />

PS: "Save files on external storage" was disabled in the printer menu for this try. It seems that this option does't change anything, since the file is still copied in the root directory (according to FTP connection)

PPS: When i copy the exact same file into the existing cache directory, it still not works regardless of which path i use in the automation "filename" which is sent as "file:///sdcard/Drill_Dust_Collector_And_Guide.gcode.3mf" or "cache/filename" which is sent as "file:///sdcard/cache/Drill_Dust_Collector_And_Guide.gcode.3mf" according to the Debug Protocol. Error is still the same.

**Comment by AdrianGarside** [comment]
I had to make a change to not always prepend file:///sdcard. Please use this version to try out the alternate possible ways to list the file:
https://github.com/greghesp/ha-bambulab/releases/tag/v2.2.2-beta2

**Comment by StefanX13** [comment]
> I had to make a change to not always prepend file:///sdcard. Please use this version to try out the alternate possible ways to list the file: https://github.com/greghesp/ha-bambulab/releases/tag/v2.2.2-beta2

Doesn't work here are two debug protocols. The first one is while trying to print with the automation, the second one is while trying to print through UI.

[home-assistant_bambu_lab_2025-09-15T08-10-08.893Z.log](https://github.com/user-attachments/files/22329753/home-assistant_bambu_lab_2025-09-15T08-10-08.893Z.log)

[home-assistant_bambu_lab_2025-09-15T08-13-07.012Z.log](https://github.com/user-attachments/files/22329754/home-assistant_bambu_lab_2025-09-15T08-13-07.012Z.log)

**Comment by StefanX13** [comment]
With my little knowledge of py i changed the last changes in coordinator.py to this:

        command["print"]["param"] = f"Metadata/plate_{plate}.gcode"
        if "//" in filepath:
            command["print"]["url"] = filepath
        else:
            command["print"]["url"] = f"file:///sdcard/{filepath}"

This seems to work now. Unfortunately none of my tries to change the URL Path was successful. 
Tried the follwing:

file:///sdcard/cache/Drill_Dust_Collector_And_Guide.gcode.3mf
file:///sdcard/Drill_Dust_Collector_And_Guide.gcode.3mf
file:///Drill_Dust_Collector_And_Guide.gcode.3mf
ftp://sdcard/cache/Drill_Dust_Collector_And_Guide.gcode.3mf
ftp://Drill_Dust_Collector_And_Guide.gcode.3mf
ftp://sdcard/Drill_Dust_Collector_And_Guide.gcode.3mf

Same error message, here are the snippet from my last tries:

```
2025-09-15 14:05:04.802 WARNING (MainThread) [custom_components.moonraker] Cannot configure moonraker instance
2025-09-15 14:05:04.802 ERROR (MainThread) [moonraker_api.websockets.websocketclient] Websocket connection error: Cannot connect to host 192.168.178.22:7125 ssl:default [Connect call failed ('192.168.178.22', 7125)]
2025-09-15 14:05:05.378 WARNING (MainThread) [custom_components.moonraker] Cannot configure moonraker instance
2025-09-15 14:05:05.378 ERROR (MainThread) [moonraker_api.websockets.websocketclient] Websocket connection error: Cannot connect to host 192.168.178.156:7125 ssl:default [Connect call failed ('192.168.178.156', 7125)]
2025-09-15 14:05:22.867 DEBUG (MainThread) [custom_components.bambu_lab] handle_service_call: print_project_file
2025-09-15 14:05:22.867 DEBUG (MainThread) [custom_components.bambu_lab.pybambu] Sent {'print': {'sequence_id': 0, 'command': 'project_file', 'param': 'Metadata/plate_1.gcode', 'url': 'file://sdcard/cache/Drill_Dust_Collector_And_Guide.gcode.3mf', 'bed_type': 'auto', 'timelapse': False, 'bed_leveling': True, 'flow_cali': False, 'vibration_cali': True, 'layer_inspect': False, 'use_ams': True, 'ams_mapping': [3], 'subtask_name': 'Drill_Dust_Collector_And_Guide.gcode.3mf', 'profile_id': '0', 'project_id': '0', 'subtask_id': '0', 'task_id': '0'}} to topic device/0938BC562600476/request
2025-09-15 14:05:22.868 DEBUG (MainThread) [custom_components.bambu_lab] Service call result: False
2025-09-15 14:05:23.011 DEBUG (H2S-Mqtt-167) [custom_components.bambu_lab.pybambu] SUBTASK_NAME: Drill_Dust_Collector_And_Guide.gcode.3mf
2025-09-15 14:05:23.954 DEBUG (H2S-Mqtt-167) [custom_components.bambu_lab.pybambu] SUBTASK_NAME: Drill_Dust_Collector_And_Guide
2025-09-15 14:05:30.083 DEBUG (MainThread) [custom_components.bambu_lab] handle_service_call: print_project_file
2025-09-15 14:05:30.085 DEBUG (MainThread) [custom_components.bambu_lab.pybambu] Sent {'print': {'sequence_id': 0, 'command': 'project_file', 'param': 'Metadata/plate_1.gcode', 'url': 'file://sdcard/Drill_Dust_Collector_And_Guide.gcode.3mf', 'bed_type': 'auto', 'timelapse': False, 'bed_leveling': True, 'flow_cali': False, 'vibration_cali': True, 'layer_inspect': False, 'use_ams': True, 'ams_mapping': [3], 'subtask_name': 'Drill_Dust_Collector_And_Guide.gcode.3mf', 'profile_id': '0', 'project_id': '0', 'subtask_id': '0', 'task_id': '0'}} to topic device/0938BC562600476/request
2025-09-15 14:05:30.086 DEBUG (MainThread) [custom_components.bambu_lab] Service call result: False
2025-09-15 14:05:30.201 DEBUG (H2S-Mqtt-167) [custom_components.bambu_lab.pybambu] SUBTASK_NAME: Drill_Dust_Collector_And_Guide.gcode.3mf
2025-09-15 14:05:30.710 DEBUG (H2S-Mqtt-167) [custom_components.bambu_lab.pybambu] SUBTASK_NAME: Drill_Dust_Collector_And_Guide
2025-09-15 14:05:43.838 DEBUG (MainThread) [custom_components.bambu_lab] handle_service_call: print_project_file
2025-09-15 14:05:43.840 DEBUG (MainThread) [custom_components.bambu_lab.pybambu] Sent {'print': {'sequence_id': 0, 'command': 'project_file', 'param': 'Metadata/plate_1.gcode', 'url': 'file://Drill_Dust_Collector_And_Guide.gcode.3mf', 'bed_type': 'auto', 'timelapse': False, 'bed_leveling': True, 'flow_cali': False, 'vibration_cali': True, 'layer_inspect': False, 'use_ams': True, 'ams_mapping': [3], 'subtask_name': 'Drill_Dust_Collector_And_Guide.gcode.3mf', 'profile_id': '0', 'project_id': '0', 'subtask_id': '0', 'task_id': '0'}} to topic device/0938BC562600476/request
2025-09-15 14:05:43.843 DEBUG (MainThread) [custom_components.bambu_lab] Service call result: False
2025-09-15 14:05:44.027 DEBUG (H2S-Mqtt-167) [custom_components.bambu_lab.pybambu] SUBTASK_NAME: Drill_Dust_Collector_And_Guide.gcode.3mf
2025-09-15 14:05:44.776 DEBUG (H2S-Mqtt-167) [custom_components.bambu_lab.pybambu] SUBTASK_NAME: Drill_Dust_Collector_And_Guide
```

**Comment by AdrianGarside** [comment]
Yes, that was the fix I was going to make. Strings are the hardest when you jump round between different programming languages.

**Comment by AdrianGarside** [comment]
I haven't been able to find anything saying that the path needs to be different for the H2 printers.

Hail mary attempt - try replacing sdcard with usb?
Also maybe try ftp:/// (3 slashes)

**Comment by StefanX13** [comment]
> I haven't been able to find anything saying that the path needs to be different for the H2 printers.
> 
> Hail mary attempt - try replacing sdcard with usb? Also maybe try ftp:/// (3 slashes)

Maybe no hail mary, but someone knows the new rules for balls that touches the landing zone and roll in the end zone (sorry ;) )
ftp:/// works fine for H2S!
Is it possible to change this in UI depending on the printer used as well?

**Comment by AdrianGarside** [comment]
Yes, that's very easy to do. Can you see if ftp:///cache/[filename] also works for files placed in a subdirectory? Or, if that doesn't work, please try ftp:////cache/[filename]

**Comment by StefanX13** [comment]
> Yes, that's very easy to do. Can you see if ftp:///cache/[filename] also works for files placed in a subdirectory? Or, if that doesn't work, please try ftp:////cache/[filename]

ftp:///cache/[filename] (3 "/") also works fine for subdirectories.

**Comment by AdrianGarside** [comment]
Confirmed that, sadly, ftp:/// doesn't work for P1s. So I do need to change the string dependent on the printer model which is annoying.

**Comment by AdrianGarside** [comment]
Please try:
https://github.com/greghesp/ha-bambulab/releases/tag/v2.2.2-beta4

**Comment by StefanX13** [comment]
Works great for me, as far as I can say after first fast tests.

**Comment by AdrianGarside** [comment]
Fixed the AMS mapping in this drop. It was completely broken. I don't know if it will work with AMS HTs yet as I can't test that:
https://github.com/greghesp/ha-bambulab/releases/tag/v2.2.3-beta1
