### ISSUE TITLE
[Bug] EXTERNAL:  P1P/S only supports single local mqtt client correctly with 1.0.4.0 firmware. Also A1 Mini has this issue.

### ISSUE THREAD

**Issue by gustafssone** [greghesp/ha-bambulab#174]
### Describe the bug

Recently bought an P1S - works generally great. 
My impression was that this integration was working solidly, until I upgraded the firmware. 
Sometimes the information gets updated, sometimes not. If I reload the integration it works sometimes. Intermittently it works, generally. Note though, if I push a change through the integration (turn on the light), that specific command always works. 
I use LAN mode, but tried enabling the communication over the network completely, (both within LAN and online), no difference.

I had version "P1P OTA version01.03.00.00（20230608)" previously.
It is now "P1 series OTA version01.04.00.00（20230807)". A hunch might be that this bug fix is causing this:
"Fixed the printer restart problem caused by continuous reconnection of MQTT using third-party tools." - see https://wiki.bambulab.com/en/p1/manual/p1p-firmware-release-history .

### To Reproduce

Install latest firmware, try to use the integration. It usually picks up some info. If I reload it it works sometimes.

### Expected Behaviour

To be able to rely on the information.
The Device tab inside Bambu Studio works fine. 
FTP works too.

### What device are you using?

P1S
(P1S is not an option in the drop down for bug reports, please add!)

### Firmware Version

01.04.00.00

### Home Assistant Version

2023.7.3

### Component Version

v1.4.8

### Log Extracts

Turned on DEBUG logging for a while, then turned it off. Made 5 prints during the day (2023-08-17):
0715-1000, 1400-1600, 1630-1730, 1830-1915, 2045-2120.
Watchdog fired is sent completely intermittently, sometimes after 15 minutes, sometimes 1-2 hours.

2023-08-15 23:16:32.090 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration bambu_lab which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-08-16 17:13:22.616 WARNING (MainThread) [custom_components.bambu_lab.pybambu] On Disconnect: Disconnected from Broker: 0
2023-08-16 17:13:22.625 WARNING (Thread-11 (listen_thread)) [custom_components.bambu_lab.pybambu] On Disconnect: Disconnected from Broker: 0
2023-08-16 17:15:08.888 WARNING (MainThread) [custom_components.bambu_lab.pybambu] On Disconnect: Disconnected from Broker: 0
2023-08-16 17:16:44.956 WARNING (Thread-404241 (listen_thread)) [custom_components.bambu_lab.pybambu] On Disconnect: Disconnected from Broker: 16
2023-08-16 17:16:44.962 WARNING (Thread-404241 (listen_thread)) [custom_components.bambu_lab.pybambu] On Disconnect: Disconnected from Broker: 16
2023-08-16 17:24:27.495 WARNING (Thread-404241 (listen_thread)) [custom_components.bambu_lab.pybambu] On Disconnect: Disconnected from Broker: 16

<<DEBUG ENABLED>>

2023-08-16 23:08:14.545 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab.pybambu] On Message: Received Message: b'{"print":{"bed_temper":25.625,"command":"push_status","msg":1,"sequence_id":"42065"}}'
2023-08-16 23:08:14.546 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-08-16 23:08:16.560 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab.pybambu] On Message: Received Message: b'{"print":{"wifi_signal":"-56dBm","command":"push_status","msg":1,"sequence_id":"42066"}}'
2023-08-16 23:08:16.560 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-08-16 23:08:20.583 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab.pybambu] On Message: Received Message: b'{"print":{"nozzle_temper":28,"command":"push_status","msg":1,"sequence_id":"42067"}}'
2023-08-16 23:08:20.584 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-08-16 23:08:40.584 DEBUG (Thread-404978) [custom_components.bambu_lab.pybambu] Watchdog fired. No data received for 20.000356674194336 seconds.
2023-08-16 23:08:40.584 DEBUG (Thread-404978) [custom_components.bambu_lab.pybambu] Watch dog fired
2023-08-16 23:08:40.585 DEBUG (Thread-404978) [custom_components.bambu_lab.pybambu] Sent {'pushing': {'sequence_id': '0', 'command': 'start'}} to topic device/<<MY_P1S_NO>>/request
2023-08-16 23:08:40.626 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab.pybambu] On Message: Received Message: b'{"print":{"upload":{"status":"idle","progress":0,"message":""},"nozzle_temper":28,"nozzle_target_temper":0,"bed_temper":25.625,"bed_target_temper":0,"chamber_temper":5,"mc_print_stage":"1","heatbreak_fan_speed":"0","cooling_fan_speed":"0","big_fan1_speed":"0","big_fan2_speed":"0","mc_percent":100,"mc_remaining_time":0,"ams_status":0,"ams_rfid_status":0,"hw_switch_state":0,"spd_mag":100,"spd_lvl":2,"print_error":0,"lifecycle":"product","wifi_signal":"-56dBm","gcode_state":"FINISH","gcode_file_prepare_percent":"0","queue_number":0,"queue_total":0,"queue_est":0,"queue_sts":0,"project_id":"0","profile_id":"0","task_id":"0","subtask_id":"0","subtask_name":"Tobera bambu x1 v3","gcode_file":"Tobera bambu x1 v3.gcode.3mf","stg":[],"stg_cur":255,"print_type":"idle","home_flag":16664,"mc_print_line_number":"8641","mc_print_sub_stage":0,"sdcard":true,"force_upgrade":false,"mess_production_state":"active","layer_num":25,"total_layer_num":25,"hms":[],"online":{"ahb":false,"rfid":false,"version":1126223550},"ams":{"ams":[{"id":"0","humidity":"1","temp":"0.0","tray":[{"id":"0","remain":-1,"k":0.035000000149011612,"n":1.3999999761581421,"tag_uid":"0000000000000000","tray_id_name":"","tray_info_idx":"GFG99","tray_type":"PETG","tray_sub_brands":"","tray_color":"FFFFFFFF","tray_weight":"0","tray_diameter":"0.00","tray_temp":"0","tray_time":"0","bed_temp_type":"0","bed_temp":"0","nozzle_temp_max":"270","nozzle_temp_min":"220","xcam_info":"000000000000000000000000","tray_uuid":"00000000000000000000000000000000"},{"id":"1","remain":-1,"k":0.035000000149011612,"n":1.3999999761581421,"tag_uid":"0000000000000000","tray_id_name":"","tray_info_idx":"GFG99","tray_type":"PETG","tray_sub_brands":"","tray_color":"161616FF","tray_weight":"0","tray_diameter":"0.00","tray_temp":"0","tray_time":"0","bed_temp_type":"0","bed_temp":"0","nozzle_temp_max":"270","nozzle_temp_min":"220","xcam_info":"00000 ...
2023-08-16 23:08:40.627 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-08-16 23:08:40.634 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab.pybambu] UNKNOWN FILAMENT IDX: 
2023-08-16 23:08:40.634 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-08-16 23:08:40.638 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-08-16 23:08:42.631 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab.pybambu] On Message: Received Message: b'{"print":{"bed_temper":25.59375,"command":"push_status","msg":1,"sequence_id":"42069"}}'
2023-08-16 23:08:42.632 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-08-16 23:08:52.674 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab.pybambu] On Message: Received Message: b'{"print":{"bed_temper":25.625,"command":"push_status","msg":1,"sequence_id":"42070"}}'
2023-08-16 23:08:52.675 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-08-16 23:09:12.675 DEBUG (Thread-404978) [custom_components.bambu_lab.pybambu] Watchdog fired. No data received for 20.000270128250122 seconds.
2023-08-16 23:09:12.675 DEBUG (Thread-404978) [custom_components.bambu_lab.pybambu] Watch dog fired
2023-08-16 23:09:12.676 DEBUG (Thread-404978) [custom_components.bambu_lab.pybambu] Sent {'pushing': {'sequence_id': '0', 'command': 'start'}} to topic device/<<MY_P1S_NO>>/request
2023-08-16 23:09:12.712 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab.pybambu] On Message: Received Message: b'{"print":{"upload":{"status":"idle","progress":0,"message":""},"nozzle_temper":28,"nozzle_target_temper":0,"bed_temper":25.625,"bed_target_temper":0,"chamber_temper":5,"mc_print_stage":"1","heatbreak_fan_speed":"0","cooling_fan_speed":"0","big_fan1_speed":"0","big_fan2_speed":"0","mc_percent":100,"mc_remaining_time":0,"ams_status":0,"ams_rfid_status":0,"hw_switch_state":0,"spd_mag":100,"spd_lvl":2,"print_error":0,"lifecycle":"product","wifi_signal":"-56dBm","gcode_state":"FINISH","gcode_file_prepare_percent":"0","queue_number":0,"queue_total":0,"queue_est":0,"queue_sts":0,"project_id":"0","profile_id":"0","task_id":"0","subtask_id":"0","subtask_name":"Tobera bambu x1 v3","gcode_file":"Tobera bambu x1 v3.gcode.3mf","stg":[],"stg_cur":255,"print_type":"idle","home_flag":16664,"mc_print_line_number":"8641","mc_print_sub_stage":0,"sdcard":true,"force_upgrade":false,"mess_production_state":"active","layer_num":25,"total_layer_num":25,"hms":[],"online":{"ahb":false,"rfid":false,"version":1126223550},"ams":{"ams":[{"id":"0","humidity":"1","temp":"0.0","tray":[{"id":"0","remain":-1,"k":0.035000000149011612,"n":1.3999999761581421,"tag_uid":"0000000000000000","tray_id_name":"","tray_info_idx":"GFG99","tray_type":"PETG","tray_sub_brands":"","tray_color":"FFFFFFFF","tray_weight":"0","tray_diameter":"0.00","tray_temp":"0","tray_time":"0","bed_temp_type":"0","bed_temp":"0","nozzle_temp_max":"270","nozzle_temp_min":"220","xcam_info":"000000000000000000000000","tray_uuid":"00000000000000000000000000000000"},{"id":"1","remain":-1,"k":0.035000000149011612,"n":1.3999999761581421,"tag_uid":"0000000000000000","tray_id_name":"","tray_info_idx":"GFG99","tray_type":"PETG","tray_sub_brands":"","tray_color":"161616FF","tray_weight":"0","tray_diameter":"0.00","tray_temp":"0","tray_time":"0","bed_temp_type":"0","bed_temp":"0","nozzle_temp_max":"270","nozzle_temp_min":"220","xcam_info":"00000 ...
2023-08-16 23:09:12.713 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-08-16 23:09:12.717 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab.pybambu] UNKNOWN FILAMENT IDX: 
2023-08-16 23:09:12.717 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-08-16 23:09:12.722 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-08-16 23:09:14.723 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab.pybambu] On Message: Received Message: b'{"print":{"wifi_signal":"-55dBm","command":"push_status","msg":1,"sequence_id":"42072"}}'
2023-08-16 23:09:14.724 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-08-16 23:09:16.736 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab.pybambu] On Message: Received Message: b'{"print":{"wifi_signal":"-56dBm","command":"push_status","msg":1,"sequence_id":"42073"}}'
2023-08-16 23:09:16.737 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-08-16 23:09:20.749 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab.pybambu] On Message: Received Message: b'{"print":{"wifi_signal":"-55dBm","command":"push_status","msg":1,"sequence_id":"42074"}}'
2023-08-16 23:09:20.750 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data

<<LOG REDACTED, Manually updated bambu_lab data + On Message: Received Message: every 4 seconds or so>>

2023-08-17 07:01:05.430 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-08-17 07:01:25.430 DEBUG (Thread-404978) [custom_components.bambu_lab.pybambu] Watchdog fired. No data received for 20.000174283981323 seconds.
2023-08-17 07:01:25.430 DEBUG (Thread-404978) [custom_components.bambu_lab.pybambu] Watch dog fired
2023-08-17 07:01:25.432 DEBUG (Thread-404978) [custom_components.bambu_lab.pybambu] Sent {'pushing': {'sequence_id': '0', 'command': 'start'}} to topic device/<<MY_P1S_NO>>/request
2023-08-17 07:01:25.467 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab.pybambu] On Message: Received Message: b'{"print":{"upload":{"status":"idle","progress":0,"message":""},"nozzle_temper":25.53125,"nozzle_target_temper":0,"bed_temper":23.375,"bed_target_temper":0,"chamber_temper":5,"mc_print_stage":"1","heatbreak_fan_speed":"0","cooling_fan_speed":"0","big_fan1_speed":"0","big_fan2_speed":"0","mc_percent":100,"mc_remaining_time":0,"ams_status":0,"ams_rfid_status":0,"hw_switch_state":0,"spd_mag":100,"spd_lvl":2,"print_error":0,"lifecycle":"product","wifi_signal":"-56dBm","gcode_state":"FINISH","gcode_file_prepare_percent":"0","queue_number":0,"queue_total":0,"queue_est":0,"queue_sts":0,"project_id":"0","profile_id":"0","task_id":"0","subtask_id":"0","subtask_name":"Tobera bambu x1 v3","gcode_file":"Tobera bambu x1 v3.gcode.3mf","stg":[],"stg_cur":255,"print_type":"idle","home_flag":16664,"mc_print_line_number":"8641","mc_print_sub_stage":0,"sdcard":true,"force_upgrade":false,"mess_production_state":"active","layer_num":25,"total_layer_num":25,"hms":[],"online":{"ahb":false,"rfid":false,"version":1126223550},"ams":{"ams":[{"id":"0","humidity":"1","temp":"0.0","tray":[{"id":"0","remain":-1,"k":0.035000000149011612,"n":1.3999999761581421,"tag_uid":"0000000000000000","tray_id_name":"","tray_info_idx":"GFG99","tray_type":"PETG","tray_sub_brands":"","tray_color":"FFFFFFFF","tray_weight":"0","tray_diameter":"0.00","tray_temp":"0","tray_time":"0","bed_temp_type":"0","bed_temp":"0","nozzle_temp_max":"270","nozzle_temp_min":"220","xcam_info":"000000000000000000000000","tray_uuid":"00000000000000000000000000000000"},{"id":"1","remain":-1,"k":0.035000000149011612,"n":1.3999999761581421,"tag_uid":"0000000000000000","tray_id_name":"","tray_info_idx":"GFG99","tray_type":"PETG","tray_sub_brands":"","tray_color":"161616FF","tray_weight":"0","tray_diameter":"0.00","tray_temp":"0","tray_time":"0","bed_temp_type":"0","bed_temp":"0","nozzle_temp_max":"270","nozzle_temp_min":"220","xcam_info": ...
2023-08-17 07:01:25.468 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-08-17 07:01:25.472 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab.pybambu] UNKNOWN FILAMENT IDX: 
2023-08-17 07:01:25.472 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-08-17 07:01:25.476 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data

<<LOG REDACTED, Manually updated bambu_lab data + On Message: Received Message: every 4 seconds or so>>

2023-08-17 12:30:49.205 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-08-17 12:30:51.219 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab.pybambu] On Message: Received Message: b'{"print":{"nozzle_temper":28.78125,"command":"push_status","msg":1,"sequence_id":"53856"}}'
2023-08-17 12:30:51.219 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-08-17 12:31:11.219 DEBUG (Thread-404978) [custom_components.bambu_lab.pybambu] Watchdog fired. No data received for 20.000194549560547 seconds.
2023-08-17 12:31:11.219 DEBUG (Thread-404978) [custom_components.bambu_lab.pybambu] Watch dog fired
2023-08-17 12:31:11.220 DEBUG (Thread-404978) [custom_components.bambu_lab.pybambu] Sent {'pushing': {'sequence_id': '0', 'command': 'start'}} to topic device/<<MY_P1S_NO>>/request
2023-08-17 12:31:11.274 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab.pybambu] On Message: Received Message: b'{"print":{"upload":{"status":"idle","progress":0,"message":""},"nozzle_temper":28.78125,"nozzle_target_temper":0,"bed_temper":26.46875,"bed_target_temper":0,"chamber_temper":5,"mc_print_stage":"1","heatbreak_fan_speed":"0","cooling_fan_speed":"0","big_fan1_speed":"0","big_fan2_speed":"0","mc_percent":100,"mc_remaining_time":0,"ams_status":0,"ams_rfid_status":0,"hw_switch_state":0,"spd_mag":100,"spd_lvl":2,"print_error":0,"lifecycle":"product","wifi_signal":"-58dBm","gcode_state":"FINISH","gcode_file_prepare_percent":"0","queue_number":0,"queue_total":0,"queue_est":0,"queue_sts":0,"project_id":"0","profile_id":"0","task_id":"0","subtask_id":"0","subtask_name":"Tobera bambu x1 v3","gcode_file":"Tobera bambu x1 v3.gcode.3mf","stg":[],"stg_cur":255,"print_type":"idle","home_flag":16696,"mc_print_line_number":"470460","mc_print_sub_stage":0,"sdcard":true,"force_upgrade":false,"mess_production_state":"active","layer_num":917,"total_layer_num":917,"hms":[],"online":{"ahb":false,"rfid":false,"version":1126223550},"ams":{"ams":[{"id":"0","humidity":"1","temp":"0.0","tray":[{"id":"0","remain":-1,"k":0.035000000149011612,"n":1.3999999761581421,"tag_uid":"0000000000000000","tray_id_name":"","tray_info_idx":"GFG99","tray_type":"PETG","tray_sub_brands":"","tray_color":"FFFFFFFF","tray_weight":"0","tray_diameter":"0.00","tray_temp":"0","tray_time":"0","bed_temp_type":"0","bed_temp":"0","nozzle_temp_max":"270","nozzle_temp_min":"220","xcam_info":"000000000000000000000000","tray_uuid":"00000000000000000000000000000000"},{"id":"1","remain":-1,"k":0.035000000149011612,"n":1.3999999761581421,"tag_uid":"0000000000000000","tray_id_name":"","tray_info_idx":"GFG99","tray_type":"PETG","tray_sub_brands":"","tray_color":"161616FF","tray_weight":"0","tray_diameter":"0.00","tray_temp":"0","tray_time":"0","bed_temp_type":"0","bed_temp":"0","nozzle_temp_max":"270","nozzle_temp_min":"220","xcam_ ...
2023-08-17 12:31:11.275 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-08-17 12:31:11.279 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab.pybambu] UNKNOWN FILAMENT IDX: 
2023-08-17 12:31:11.279 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-08-17 12:31:11.283 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-08-17 12:31:17.288 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab.pybambu] On Message: Received Message: b'{"print":{"bed_temper":26.4375,"wifi_signal":"-60dBm","command":"push_status","msg":1,"sequence_id":"53858"}}'
2023-08-17 12:31:17.289 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-08-17 12:31:19.301 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab.pybambu] On Message: Received Message: b'{"print":{"wifi_signal":"-58dBm","command":"push_status","msg":1,"sequence_id":"53859"}}'

<<LOG REDACTED, Manually updated bambu_lab data + On Message: Received Message: every 4 seconds or so>>

2023-08-17 13:01:11.439 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-08-17 13:01:13.451 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab.pybambu] On Message: Received Message: b'{"print":{"bed_temper":25.53125,"command":"push_status","msg":1,"sequence_id":"54301"}}'
2023-08-17 13:01:13.451 DEBUG (Thread-404241 (listen_thread)) [custom_components.bambu_lab] Manually updated bambu_lab data
2023-08-17 13:01:33.451 DEBUG (Thread-404978) [custom_components.bambu_lab.pybambu] Watchdog fired. No data received for 20.000341176986694 seconds.
2023-08-17 13:01:33.452 DEBUG (Thread-404978) [custom_components.bambu_lab.pybambu] Watch dog fired
2023-08-17 13:01:33.453 DEBUG (Thread-404978) [custom_components.bambu_lab.pybambu] Sent {'pushing': {'sequence_id': '0', 'command': 'start'}} to topic device/<<MY_P1S_NO>>/request

<<DEBUG DISABLED>>

2023-08-17 13:52:48.869 WARNING (MainThread) [custom_components.bambu_lab.pybambu] On Disconnect: Disconnected from Broker: 0
2023-08-17 18:56:14.105 WARNING (Thread-667606 (listen_thread)) [custom_components.bambu_lab.pybambu] On Disconnect: Disconnected from Broker: 16
2023-08-17 18:56:14.112 WARNING (Thread-667606 (listen_thread)) [custom_components.bambu_lab.pybambu] On Disconnect: Disconnected from Broker: 16

**Comment by slynn1324** [comment]
I think I'm seeing something similar.... seems to stop working periodically unless I restart HA and then it will work again for awhile.  Bambu Studio never seems to have an issue connecting from multiple PCs at the same time to monitor... and they're connecting over MQTT as well - so maybe need to dig into what happens in there and emulate it or something.

**Comment by QuiNz0r** [comment]
very same issues for me

**Comment by QuiNz0r** [comment]
any update? This happens very often for me, almost makes it unusable

**Comment by aled2305** [comment]
I'm experiencing the same issue with a X1C

**Comment by AdrianGarside** [comment]
@gustafssone back from an extended holiday so I'll see if I can reproduce this. So far I see you have multiple listener threads active simultaneously which isn't expected and most of them have ridiculously high ID numbers which suggests your HA instance has been burning threads somehow (could be any integration causing this).

Can you expand more on 'Sometimes the information gets updated, sometimes not.' - the recently added watch dog was because it's been observed that something is causing the printer to stop sending mqtt data and so we have to tell it to start sending it again. And in your log snippets it seems the restart successfully sent the latest state of the printer and then resumed getting data every few seconds as expected. What was happening in the log at the point updates got missed?

**Comment by AdrianGarside** [comment]
Hmm. Upgraded my P1P to the latest firmware and now I'm not receiving *any* data from the printer mqtt connection while mqtt explorer is working just fine. Everything seems to be connected fine - just nothing being received at all.

**Comment by QuiNz0r** [comment]
> Hmm. Upgraded my P1P to the latest firmware and now I'm not receiving *any* data from the printer mqtt connection while mqtt explorer is working just fine. Everything seems to be connected fine - just nothing being received at all.

I have this issue often too, only restarting printer and home assistant helps for me.

I have a feeling it has something to do with Bambu Studio, when I connect to my printer to view the camera and their mqtt info, it has a chance (not always) of bricking my hacs integration

**Comment by AdrianGarside** [comment]
Restarting the printer restored data being received by the integration. Briefly. And yet the data is flowing consistently to mqtt explorer. Aha, restarted the printer again and now I have data flowing to my two HA instances (real + test) but mqtt explorer is no longer being sent anything. And disconnecting/reconnecting has the same issue I saw with HA - the connection succeeds but it's never sent anything.

**Comment by QuiNz0r** [comment]
> Restarting the printer restored data being received by the integration. Briefly. And yet the data is flowing consistently to mqtt explorer. Aha, restarted the printer again and now I have data flowing to my two HA instances (real + test) but mqtt explorer is no longer being sent anything. And disconnecting/reconnecting has the same issue I saw with HA - the connection succeeds but it's never sent anything.

Interesting. Yea I think it somehow only likes to feed one instance with data. Weird

**Comment by AdrianGarside** [comment]
That was my initial thought too but it doesn't seem that simple as I currently have orca slicer, bambu studio, bambu handy and one of my HA instance (test one) receiving data successfully - only the second HA instance (production) and mqtt explorer aren't getting data.

Opened an issue:
https://github.com/bambulab/BambuStudio/issues/2404

**Comment by gustafssone** [comment]
@AdrianGarside nothing really happens when it starts/stop working. Hence I have no clue. I do sometimes a restart of my HA instance (docker updating image) and/or entities requiring full restart when being modified. Could be that I just haven't boiled it down to that being a factor when reestablishing connection. Bambu Studio loses connection whenever my desktop computer goes into hibernation, meaning it is not utilizing any printer connection, so thats a factor too. Could be why it is so intermittent for me. Glad to see I'm not the only one experiencing this!

**Comment by AdrianGarside** [comment]
Seems like only the latest connection gets data. The rest just silently don't but without dropping the connection. So when I started mqtt explorer, my working HA instance stopped getting payloads but when I disconnected mqtt explorer it started getting them again.

**Comment by stephack** [comment]
I also started having these issues after upgrading to 1.04 firmware. As stated above, I seems that only one "application" can receive updates at a time. Either HA data is updated or Bambu Studio/Orca is updated. With 1.03 I was able to have both applications connected and functioning at the same time. With 1.04 connecting with either application, seems to break the other.

**Comment by AdrianGarside** [comment]
@stephack presumably you're running in lan mode? In cloud mode BS/Orca/Handy are connected to their cloud mqtt server that duplicates the data and I'm not seeing any issues with that able to service multiple clients. It's only the local mqtt that will only push data to the most recently connected client in a stack.

**Comment by stephack** [comment]
> @stephack presumably you're running in lan mode? In cloud mode BS/Orca/Handy are connected to their cloud mqtt server that duplicates the data and I'm not seeing any issues with that able to service multiple clients. It's only the local mqtt that will only push data to the most recently connected client in a stack.

Correct, I'm in Lan Only mode with a P1S (sorry, forgot to include those details). It worked perfectly in Lan mode on 1.03 but started having this issue on 1.04 f/w.

**Comment by AdrianGarside** [comment]
Unfortunately the fix for lan mode will need to come from Bambu. The best I can do is resurrect the cloud mode mqtt connection (I know how to) for those folk who run in cloud mode but also need > 1 connections to the local mqtt. Which is probably not many.

**Comment by AdrianGarside** [comment]
@stephack if you have multiple instances of bambu studio open - do they all work? If you also then open Orca do the Bambu Studio instances keep working? I'm wondering if the network plugin thing means that all instances of bamby studio/orca slicer count as a single connection the local mqtt.

**Comment by stephack** [comment]
> 

- Opened Bambu and tested by toggling chamber light.
- Opened Orca as well and tested. By apps appears to control the light and also sync changes within a few seconds
However, after a while (less than a minute) the Bambu Studio lost it's connection to the printer (orange "Failed to connect" error) and could not reconnect. I had to close out both apps completely to get the Bambu Studio app to reconnect to the printer.

**Comment by AdrianGarside** [comment]
@QuiNz0r @slynn1324 @aled2305 are you running in cloud mode and seeing this _without_ running mqtt explorer or another instance of home assistant simultaneously trying to connect to the printer? 

Lan mode is going to be broken until Bambu fix their regression - you won't be able to use home assistant and bambu studio/orc/handy app reliably together - they'll all break each other.

**Comment by piitaya** [comment]
> Unfortunately the fix for lan mode will need to come from Bambu. The best I can do is resurrect the cloud mode mqtt connection (I know how to) for those folk who run in cloud mode but also need > 1 connections to the local mqtt. Which is probably not many.

I do not use lan mode so Bambuslicer is connected to cloud mqtt. HA to cloud mqtt.
It can also be nice for development to have cloud mqtt on HA so it will not broken bambulab integration on my HA production during development of this custom integration.

**Comment by AdrianGarside** [comment]
Yes, I’m planning to resurrect the option to connect via Bambu cloud mqtt. That will enable use of both P1Touch and this integration. Or two HA instances, one cloud one local, which I’ll probably use so I can test without breaking my production HA instance.

**Comment by aled2305** [comment]
@AdrianGarside That is correct, I am running in cloud mode with only a single instance of HA, Bambu Studio and the Handy App connected. If you'd like me to test anything or send any logs etc... please let me know.

**Comment by AdrianGarside** [comment]
@aled2305  just saw you are seeing this with an X1C as well. This issue is unique to the latest P1 firmware. You are hitting something different.

**Comment by AdrianGarside** [comment]
Added back cloud mode mqtt connection support to allow use of P1Touch and Home Assistant (or, in my case, a production and test instance of home assistant) to both be able to connect to the printer.

**Comment by Faasteer** [comment]
> Added back cloud mode mqtt connection support to allow use of P1Touch and Home Assistant (or, in my case, a production and test instance of home assistant) to both be able to connect to the printer.

This is great news, this bug was driving me crazy - I love your integration, but this one was almost unusable for me. I'm already installing the new version and looking forward to testing it out.

Thanks for the great work!

**Comment by Faasteer** [comment]
I just came home and checked it out. Lan only mode is set to OFF. I tried it from the mobile app and from the local IP of my HA too. I've also tried completely removing the integration/restarting HA/installing the integration/restarting again. 

And some of it worked. So I apologize for the unnecessary "alarm", it was obviously some local problem of mine.

**Comment by AdrianGarside** [comment]
With the 1.5.0 release it should be possible to switch mqtt mode without an integration reload, HA restart or integration reinstall (I did it a bunch testing) but there’s enough complexity that there may be edges cases where a restart or reinstall fixes something up.

**Comment by jkadin** [comment]
I'm not sure if this is the correct place to ask this, but do you know if it's possible for HA to detect if Bambu Studio is running on the network and temporarily disable the Bambu integration until it closes? I'm using a P1P in LAN mode and this would be a helpful workaround until Bambu fixes their firmware change, assuming they do.

**Comment by AdrianGarside** [comment]
There's no way to detect directly that Bambu Studio is running. I can potentially make the integration report the broken state better - detect connection is not dropped but complete lack of any data being received. But if the integration 'won', then in Lan Mode, Bambu Studio will be broken until the integration stops running.

**Comment by AdrianGarside** [comment]
Added an experimental workaround for this P1/A1 limitation:
https://github.com/greghesp/ha-bambulab/releases/tag/v1.9.3-dev3-manualrefresh

**Comment by AdrianGarside** [comment]
Joined the beta firmware and this appears to be fixed in the latest beta 01.04.50.19 firmware.

**Comment by pe5er** [comment]
This is also an issue on the A1 Mini, but hopefully will be fixed in the next firmware update.

**Comment by AdrianGarside** [comment]
This is fixed in the P1P/S 1.05.0.0 firmware version.

**Comment by AdrianGarside** [comment]
> This is also an issue on the A1 Mini, but hopefully will be fixed in the next firmware update.

What is the firmware version of the A1 Mini currently? And it's still broken?

**Comment by gustafssone** [comment]
Seems to be working fine for me too, just upgraded. Running latest firmware on P1S.

**Comment by pe5er** [comment]
> > This is also an issue on the A1 Mini, but hopefully will be fixed in the next firmware update.
> 
> What is the firmware version of the A1 Mini currently? And it's still broken?

It's still broken I'm afraid, every time I start a new print in Bambu Studio I have to close Bambu Sutdio and then force refresh data in homeassistant.

I'm on firmware version 01.01.02.00 - I can see that there is a newer version (01.01.02.00) available, but the printer doesn't see an update. Perhaps it can't update when on LAN-only mode (i'm new to this).

Once I've done the update i'll get back to you

**Comment by AdrianGarside** [comment]
Yes it’s not possible to upgrade the printer in lan only mode.
