### ISSUE TITLE
[Bug] China: Failed to connect. Check credentials

### ISSUE THREAD

**Issue by Miaoerr** [greghesp/ha-bambulab#739]
### Home Assistant Version

2024.11.1

### Bambu Lab Integration Version

v2.0.36

### Describe the bug

When trying to connect to bambu lab cloud (China) I got the message "A verification code is required.", Then I received the text verification code and filled in the input box, Then I get the message, "Failed to connect. Check credentials". I don't know how to enable debug log with a not intsalled integration, but in general log I found this entry:

> 此错误来自自定义集成。
>
>日志记录器: custom_components.bambu_lab
>来源: custom_components/bambu_lab/config_flow.py:193
>集成: Bambu Lab (文档, 问题)
>首次出现: 10:05:01 (1 次总计出现)
>上次记录: 10:05:01
>
>Failed to connect with error code ('list index out of range',)

I think I'm still being intercepted by cloudflare capTCHA, but the previous issue has been closed.

### To Reproduce

Setup
Integrations
Add Integration
Select Bambu Lab
Select Cloud
Select China
Enter Phone Number and Password
Click Login
Enter Verification Code
Click Login

### Expected Behaviour

Successful connection to Bambu Lab Cloud.

### What device are you using?

P1S

### Diagnostic Output

```shell
Not possible, first time installation
```

### Log Extracts

```shell
此错误来自自定义集成。

日志记录器: custom_components.bambu_lab
来源: custom_components/bambu_lab/config_flow.py:193
集成: Bambu Lab (文档, 问题)
首次出现: 10:05:01 (1 次总计出现)
上次记录: 10:05:01

Failed to connect with error code ('list index out of range',)
```

**Comment by Miaoerr** [comment]
I have used v2.0.34, v2.0.35, v2.0.36, v2.0.37-dev1, but they all failed to log in successfully.

**Comment by AdrianGarside** [comment]
Soes 2.0.37-dev1 give different error output?

**Comment by AdrianGarside** [comment]
Add this to your configuration.yaml to have debug logs during initial setup: 
```logger:
  default: info
  logs:
    custom_components.bambu_lab: debug```

**Comment by Miaoerr** [comment]
After I set up logger, this is the log for v2.0.37-dev1:
>此错误来自自定义集成。
>
>日志记录器: custom_components.bambu_lab.pybambu
>来源: custom_components/bambu_lab/pybambu/bambu_cloud.py:135
>集成: Bambu Lab (文档, 问题)
>首次出现: 10:45:07 (1 次总计出现)
>上次记录: 10:45:07
>
>Login attempt failed with error code: 400

>此错误来自自定义集成。
>
>日志记录器: custom_components.bambu_lab
>来源: custom_components/bambu_lab/config_flow.py:187
>集成: Bambu Lab (文档, 问题)
>首次出现: 10:45:07 (1 次总计出现)
>上次记录: 10:45:07
>
>Failed to connect with error code (400, '{"code":2,"error":"Invalid or already taken"}')

This is the log for v2.0.36:
>此错误来自自定义集成。
>
>日志记录器: custom_components.bambu_lab
>来源: custom_components/bambu_lab/config_flow.py:193
>集成: Bambu Lab (文档, 问题)
>首次出现: 10:47:51 (1 次总计出现)
>上次记录: 10:47:51
>
>Failed to connect with error code ('Failed to perform, curl: (6) Could not resolve host: api.bambulab.cn. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.',)

But I used my Home Assistant network to access api.bambulab.cn and it seems to be accessible normally, but it shows:

```
d28f3b430328:/config# curl api.bambulab.cn
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
```

**Comment by AdrianGarside** [comment]
That log output is still errors only. There should be a bunch of surround debug logs to give context what the integration was doing at the time.

But the errors seem inconsistent. 2.0.36 is getting told the endpoint permanently moved but 2.0.37-dev1 was able to successfully connect but was told the code you entered (I assume you entered a code?) was not correct.

**Comment by Miaoerr** [comment]
I tried to restart homeassistant for many times, but logger did not seem to take effect. I updated homeassistant to version 2024.11.2, but an error occurred when using version v2.0.37-dev1:
>homeassistant  | 2024-11-16 13:15:58.466 DEBUG (SyncWorker_28) [custom_components.bambu_lab.pybambu] Getting accessToken from Bambu Cloud
>homeassistant  | 2024-11-16 13:15:58.466 DEBUG (SyncWorker_28) [custom_components.bambu_lab.pybambu] Curl library is unavailable.
When I tried v2.0.36 again, I could not receive the SMS verification code, after many attempts, maybe I need to wait a while before trying again.

**Comment by xperiments** [comment]
Guys, china has changed the way login is done
We can't get anymore the user from the auth token

But china users has a way to see it, so it can be in the config...

![image](https://github.com/user-attachments/assets/f3172545-7094-43ac-82d4-bcefc2c1f6f7)

**Comment by xperiments** [comment]
ATM is the info we have, I am waiting to update to see if there is a easy way to get it

**Comment by AdrianGarside** [comment]
> > homeassistant  | 2024-11-16 13:15:58.466 DEBUG (SyncWorker_28) [custom_components.bambu_lab.pybambu] Curl library is unavailable.

Won't be sufficient to help you but this error is fixed in:
https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.37-dev2

**Comment by AdrianGarside** [comment]
> I tried to restart homeassistant for many times, but logger did not seem to take effect. I updated homeassistant to version 2024.11.2, but an error occurred when using version v2.0.37-dev1:

Formatting error hid the critical first line. Fixed it now.

**Comment by xperiments** [comment]
@AdrianGarside I am them a little lost about the changes

You have changed the workflow, but actually china users do what?

They need to ask for 2FA? And in that reply we get the username?

**Comment by AdrianGarside** [comment]
The authtoken we get back is an encoded json string and you can decode it and get the username out of it. To use the authtoken for login we need both the authtoken and the username (despite it being part of the authtoken!). That's still the case outside China. But in China the authToken is now different and doesn't include the username - but we still need that to be able to login using the authtoken. The username is u_<digits> - not the phone number or email the end user thinks of as their user name.

**Comment by Miaoerr** [comment]
> > 我尝试重启homeassistant很多次，但是logger好像没有生效，我更新了homeassistant到2024.11.2版本，但是使用v2.0.37-dev1版本的时候出现错误：
> 
> 格式错误导致关键的第一行不显示。现已修复。

Thank you very much, this does fix the issue, although I still can't receive the verification code to try the next step, this should be a problem with Bambu SMS service, I will try again later.
This is log：
> homeassistant  | 2024-11-16 15:41:37.483 DEBUG (MainThread) [custom_components.bambu_lab] Found 0 existing config entries for the integration.
> homeassistant  | 2024-11-16 15:41:47.339 DEBUG (SyncWorker_12) [custom_components.bambu_lab.pybambu] Getting accessToken from Bambu Cloud
> homeassistant  | 2024-11-16 15:41:47.763 DEBUG (SyncWorker_12) [custom_components.bambu_lab.pybambu] Response: 200
> homeassistant  | 2024-11-16 15:41:47.763 DEBUG (SyncWorker_12) [custom_components.bambu_lab.pybambu] Received verifyCode response

**Comment by AdrianGarside** [comment]
I've definitely seen in my testing that if I try to login too many times, maybe if I'm not actually proceeding and using a recieved code, that it stops sending me the codes for quite some time.

**Comment by looxonline** [comment]
> The authtoken we get back is an encoded json string and you can decode it and get the username out of it. To use the authtoken for login we need both the authtoken and the username (despite it being part of the authtoken!). That's still the case outside China. But in China the authToken is now different and doesn't include the username - but we still need that to be able to login using the authtoken. The username is u_digits - not the phone number or email the end user thinks of as their user name.

This has changed for login requests coming from the Chinese region and will likely change for others too. The token is no longer a JWT that contains the userID.

**Comment by AdrianGarside** [comment]
Please try this version which has a fix to add a backup mechanism retrieve the userid if the authtoken doesn't work:
https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.38-dev1

**Comment by flyingnight** [comment]
> Please try this version which has a fix to add a backup mechanism retrieve the userid if the authtoken doesn't work: https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.38-dev1

Still unavailable

**Comment by Miaoerr** [comment]
> Please try this version which has a fix to add a backup mechanism retrieve the userid if the authtoken doesn't work: https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.38-dev1

This is the log for v2.0.38-dev1, Now I received the SMS verification code and filled it in and submitted the login request:

> homeassistant  | 2024-11-17 13:01:19.167 DEBUG (MainThread) [custom_components.bambu_lab] Found 0 existing config entries for the integration.
> homeassistant  | 2024-11-17 13:01:31.219 DEBUG (SyncWorker_35) [custom_components.bambu_lab.pybambu] Getting accessToken from Bambu Cloud
> homeassistant  | 2024-11-17 13:01:32.944 DEBUG (SyncWorker_35) [custom_components.bambu_lab.pybambu] Response: 200
> homeassistant  | 2024-11-17 13:01:32.945 DEBUG (SyncWorker_35) [custom_components.bambu_lab.pybambu] Received verifyCode response
> homeassistant  | 2024-11-17 13:01:47.814 DEBUG (SyncWorker_34) [custom_components.bambu_lab.pybambu] Attempting to connect with provided verification code.
> homeassistant  | 2024-11-17 13:01:55.326 DEBUG (SyncWorker_34) [custom_components.bambu_lab.pybambu] Response: 200
> homeassistant  | 2024-11-17 13:01:55.326 DEBUG (SyncWorker_34) [custom_components.bambu_lab.pybambu] Authentication successful.
> homeassistant  | 2024-11-17 13:01:55.327 ERROR (MainThread) [custom_components.bambu_lab] Failed to connect with error code ('list index out of range',)

**Comment by AdrianGarside** [comment]
Looks like we're getting a success response but the json doesn't have the expected 'accessToken' entry that it should have. I'll push a new version with more logging to see if that sheds light on things - you may need to redact logs you get from that so it doesn't have anything revealing in it. Ah... actually I think I see where the error is coming from.

**Comment by AdrianGarside** [comment]
https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.38-dev2

**Comment by Miaoerr** [comment]
> v2.0.38-dev2

Thank you very much. I successfully logged in China with v2.0.38-dev2 and got my P1S device.

**Comment by AdrianGarside** [comment]
Can you add w/ any necessary redaction the debug log so I can confirm the code behavior?

**Comment by Miaoerr** [comment]
Yes, of course. Attached is the log I extracted. Part of the account information has been filtered.
[ha-bambu.log](https://github.com/user-attachments/files/17789210/ha-bambu.log)

**Comment by AdrianGarside** [comment]
Great the new code ran as expected.
